notes=open("bc.txt", "r+")
str=notes.read(2)
print ("read string is :",str)
position=notes.tell()
print("current file position;",position)
position=notes.seek(0,0)
str=notes.read(11)
print("again read string is:",str)
notes.close()
